### ISSUE TITLE
Test PrebuiltIndexChecker fails since 20230613

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ua#149] opened 2023-06-14 08:50 UTC
for example 
https://download.eclipse.org/eclipse/downloads/drops4/I20230613-1050/testresults/html/org.eclipse.ua.tests.doc_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
could not open: index

java.lang.AssertionError: could not open: index
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.ua.tests.doc.internal.linkchecker.PrebuiltIndexChecker.validateIndex(PrebuiltIndexChecker.java:69)
at org.eclipse.ua.tests.doc.internal.linkchecker.PrebuiltIndexChecker.testJdtIsvIndex(PrebuiltIndexChecker.java:57)

```

**Comment by iloveeclipse** [comment] 2023-06-14 08:54
See https://github.com/eclipse-platform/eclipse.platform.ua/pull/148 / https://github.com/eclipse-platform/.github/issues/130

**Comment by akurtakov** [comment] 2023-06-14 09:10
Duplicate of https://github.com/eclipse-platform/eclipse.platform.ua/pull/148

**Closed by akurtakov** 2023-06-14 09:10 UTC
